# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from ds import Img_map, get_test_map2
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from ds import create_map
from distribut_images import distribut

from PyQt5 import QtCore, QtGui, QtWidgets
import sds_qrc

m = create_map()
m.forward()
m.forward()
m.forward()
m.turn_left()
m.forward()
m.turn_right()
m.draw_map()




class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1218, 662)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 300, 112, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 50, 112, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(1060, 290, 112, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 540, 112, 34))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 120, 751, 371))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 131, 61))
        self.label_2.setObjectName("label_2")
        self.label_2.setText("提醒")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(1010, 450, 191, 161))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "向左转"))
        self.pushButton_2.setText(_translate("Dialog", "向前走"))
        self.pushButton_3.setText(_translate("Dialog", "向右转"))
        self.pushButton_4.setText(_translate("Dialog", "向后转"))
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        self.label.setScaledContents(True)
        self.label_3.setScaledContents(True)
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))
        self.pushButton.clicked.connect(self.turn_left)
        self.pushButton_3.clicked.connect(self.turn_right)
        self.pushButton_2.clicked.connect(self.forward)
        self.pushButton_4.clicked.connect(self.turn_back)

    def turn_left(self):
        m.turn_left()
        self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))

    def turn_right(self):
        m.turn_right()
        self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))

    def turn_back(self):
        m.turn_back()
        self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))

    def forward(self):
        r = m.forward()
        if not r:
            self.label_2.setText("此路不通")
        else:
            self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))


class UiHello(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(964, 663)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(790, 600, 141, 51))
        self.pushButton.setStyleSheet("background-color: rgb(255, 170, 0);\n"
                                      "font: 26pt \"SimSun-ExtB\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(Dialog.close)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(0, 0, 1221, 661))
        self.listView.setStyleSheet("background-image:url(:/fm.jpg)")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "开始"))


class MainWindow(QtWidgets.QWidget):
    switch_window = QtCore.pyqtSignal(str)

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setWindowTitle('Main Window')
        self.resize(1218, 662)

        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(60, 300, 112, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 50, 112, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self)
        self.pushButton_3.setGeometry(QtCore.QRect(1060, 290, 112, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 540, 112, 34))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(210, 120, 751, 371))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 131, 61))
        self.label_2.setObjectName("label_2")
        self.label_2.setText("提醒")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(1010, 450, 191, 161))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(self)

        layout = QtWidgets.QGridLayout()

        self.setLayout(layout)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "向左转"))
        self.pushButton_2.setText(_translate("Dialog", "向前走"))
        self.pushButton_3.setText(_translate("Dialog", "向右转"))
        self.pushButton_4.setText(_translate("Dialog", "向后转"))
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        self.label.setScaledContents(True)
        self.label_3.setScaledContents(True)
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))
        self.pushButton.clicked.connect(self.turn_left)
        self.pushButton_3.clicked.connect(self.turn_right)
        self.pushButton_2.clicked.connect(self.forward)
        self.pushButton_4.clicked.connect(self.turn_back)

    def turn_left(self):
        m.turn_left()
        self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))

    def turn_right(self):
        m.turn_right()
        self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))

    def turn_back(self):
        m.turn_back()
        self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))

    def forward(self):
        r = m.forward()
        if not r:
            self.label_2.setText("此路不通")
        else:
            self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))


class Login(QtWidgets.QWidget):
    switch_window = QtCore.pyqtSignal()

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setWindowTitle('Login')
        self.resize(964, 663)

        layout = QtWidgets.QGridLayout()
        self.pushButton = QtWidgets.QPushButton('开始')
        self.pushButton.setGeometry(QtCore.QRect(790, 600, 141, 51))
        self.pushButton.setStyleSheet("background-color: rgb(255, 170, 0);\n"
                                      "font: 26pt \"SimSun-ExtB\";")
        self.pushButton.setObjectName("开始")
        self.pushButton.clicked.connect(self.login)
        self.pushButton.raise_()
        layout.addWidget(self.pushButton)
        self.listView = QtWidgets.QListView()
        self.listView.setGeometry(QtCore.QRect(0, 0, 1221, 661))
        self.listView.setStyleSheet("background-image:url(:/fm.jpg)")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        layout.addWidget(self.listView)

        self.setLayout(layout)

    def login(self):
        self.switch_window.emit()


class Controller:

    def __init__(self):
        pass

    def show_login(self):
        self.login = Login()
        self.login.switch_window.connect(self.show_main)
        self.login.show()

    def show_main(self):
        self.window = MainWindow()
        self.login.close()
        self.window.show()


if __name__ == "__main__":
    # app = QApplication(sys.argv)
    # MainWindow = QMainWindow()
    # hello_ui = UiHello()
    # main_ui = Ui_Dialog()
    # main_ui.setupUi(MainWindow)
    #
    # MainWindow.show()
    # secondwindow = QMainWindow()
    # hello_ui.setupUi(secondwindow)
    # secondwindow.show()
    #
    # sys.exit(app.exec_())
    app = QtWidgets.QApplication(sys.argv)
    controller = Controller()
    controller.show_login()
    sys.exit(app.exec_())
