# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from ds import Img_map, get_test_map2
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from ds import create_map
from distribut_images import distribut

from PyQt5 import QtCore, QtGui, QtWidgets

m = create_map()
m.draw_map()


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1218, 662)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 300, 112, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 50, 112, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(1060, 290, 112, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 540, 112, 34))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 120, 751, 371))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 131, 61))
        self.label_2.setObjectName("label_2")
        self.label_2.setText("提醒")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(1010, 450, 191, 161))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "向左转"))
        self.pushButton_2.setText(_translate("Dialog", "向前走"))
        self.pushButton_3.setText(_translate("Dialog", "向右转"))
        self.pushButton_4.setText(_translate("Dialog", "向后转"))
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        self.label.setScaledContents(True)
        self.label_3.setScaledContents(True)
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))
        self.pushButton.clicked.connect(self.turn_left)
        self.pushButton_3.clicked.connect(self.turn_right)
        self.pushButton_2.clicked.connect(self.forward)
        self.pushButton_4.clicked.connect(self.turn_back)

    def turn_left(self):
        m.turn_left()
        self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))

    def turn_right(self):
        m.turn_right()
        self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))

    def turn_back(self):
        m.turn_back()
        self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))

    def forward(self):
        r = m.forward()
        if not r:
            self.label_2.setText("此路不通")
        else:
            self.label_2.setText("提醒")
        self.label.setPixmap(QtGui.QPixmap(m.current_path))
        m.draw_map()
        self.label_3.setPixmap(QtGui.QPixmap("map.jpg"))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)

    MainWindow.show()

    sys.exit(app.exec_())
